blueprint:
  name: ESP32 MQTT Reminder V4
  description: Envia lembretes via MQTT para ESP32 usando Schedule
  domain: automation

  input:
    schedule_entity:
      name: Schedule
      selector:
        entity:
          domain: schedule

    message_text:
      name: Mensagem do lembrete
      selector:
        text:

    mqtt_topic:
      name: Tópico MQTT
      default: esp32/notify
      selector:
        text:

    target_id:
      name: ID do dispositivo (0 = broadcast)
      default: "0"
      selector:
        text:

mode: single

trigger:
  - platform: state
    entity_id: !input schedule_entity
    from: "off"
    to: "on"

action:
  - service: mqtt.publish
    data:
      topic: !input mqtt_topic
      payload: >
        {{ ( !input target_id ) ~ '|' ~ ( !input message_text ) }}
