blueprint:
  name: ESP32 MQTT Reminder
  domain: automation

  input:
    schedule_entity:
      selector:
        entity:
          domain: schedule

    mqtt_topic:
      default: esp32/notify
      selector:
        text:

    payload:
      name: Payload MQTT (string final)
      selector:
        text:

mode: single

trigger:
  - platform: state
    entity_id: !input schedule_entity
    from: "off"
    to: "on"

action:
  - service: mqtt.publish
    data:
      topic: !input mqtt_topic
      payload: !input payload
