blueprint:
  name: "Abrir App da TV TCL via Alexa Devices V2"
  description: "Abre aplicativos (YouTube, Netflix, Prime Video, Premiere) na TV TCL/Google TV usando Alexa Devices (send_text_command)."
  domain: script

mode: queued
icon: mdi:television

fields:

  app:
    name: "Aplicativo"
    description: "Escolha qual app abrir na TV TCL."
    required: true
    selector:
      select:
        multiple: false
        options:
          - label: "YouTube"
            value: youtube
          - label: "Netflix"
            value: netflix
          - label: "Prime Video"
            value: prime
          - label: "Premiere"
            value: premiere

  alexa_notify:
    name: "Dispositivo Alexa (Speak)"
    description: "Entidade notify do dispositivo Alexa que enviará o comando."
    required: true
    selector:
      entity:
        multiple: false
        filter:
          - domain: notify
            integration: alexa_devices
            entity_id: "*speak*"
sequence:

  - variables:
      selected_entity: "{{ alexa_notify }}"
      alexa_device_id: "{{ device_id(selected_entity) }}"
      chosen_app: "{{ app }}"

  - choose:

      - conditions: "{{ chosen_app == 'youtube' }}"
        sequence:
          - action: alexa_devices.send_text_command
            data:
              device_id: "{{ alexa_device_id }}"
              text_command: "Abrir YouTube Smart TV"

      - conditions: "{{ chosen_app == 'netflix' }}"
        sequence:
          - action: alexa_devices.send_text_command
            data:
              device_id: "{{ alexa_device_id }}"
              text_command: 'Abrir Netflix Smart TV'

      - conditions: "{{ chosen_app == 'prime' }}"
        sequence:
          - action: alexa_devices.send_text_command
            data:
              device_id: "{{ alexa_device_id }}"
              text_command: "Abrir Prime Video Smart TV"

      - conditions: "{{ chosen_app == 'premiere' }}"
        sequence:
          - action: alexa_devices.send_text_command
            data:
              device_id: "{{ alexa_device_id }}"
              text_command: "Abrir Premiere Smart TV"
